[project]
name = "code"
version = "0.1.0"
description = "Application de traitement d'images (reconnaissance de vêtements) par API"
readme = "README.md"
authors = [
    { name = "Anthony", email = "anthony.arrighi@orange.fr" }
]
requires-python = ">=3.9"
dependencies = [
    "matplotlib>=3.9.4",
    "pathlib>=1.0.1",
    "pillow>=11.3.0",
    "python-dotenv>=1.2.1",
    "requests>=2.32.5",
    "tqdm>=4.70.1",
]

[project.scripts]
code = "code:main"

[build-system]
requires = ["uv_build>=0.12.21,<0.13.0"]
build-backend = "uv_build"
